### ISSUE TITLE
Convert shell script to native swift code

### ISSUE THREAD

**Issue by haze** [DrabWeb/Pomf.cat-Uploader#1]
There is no reason to use the shell script if you are writing in a different language.

**Comment by DrabWeb** [comment]
Yeah, using the bash script was mainly me being lazy and not knowing how to use networking libraries at the time. I'll probably just rewrite the whole thing when I get a chance

**Comment by haze** [comment]
If anything I'd like to do this. At some point (hopefully before you) Ill open a pull request ;)
